### PR TITLE
Docs: additional Next.js helper information

### LINKED ISSUE #233: Document `next-tinacms-json` default object workaround
See notes from — https://github.com/tinacms/tinacms/issues/676

### PR DESCRIPTION
**Pull request by kendallstrautman**
This PR adds documentation on:

- `useGlobalJsonForm`
- `inlineJsonForm`
- `useLocalMarkdownForm`
- `useGlobalMarkdownForm`
- Updates docs on the recent deprecation of `liveRemarkForm` in lieu of `inlineRemarkForm`.
- Closes #233

### CODE REVIEW

**Comment by kendallstrautman** [comment]
Gatsby builds needs the mailchimp endpoint set up in gatsby cloud it seems

**Review by DirtyF — COMMENTED** [review]
Nice read, should we move the edit Markdown part to its own page, like we do for Gatsby?

**Comment by kendallstrautman** [comment]
yeah that might be a good idea @DirtyF

**Comment by DirtyF** [comment]
Edit JSON

**Review by ncphillips — APPROVED** [review]

**Pull request merged**
